classes:
  fighter:
    name: '&cFighter'
    icon: IRON_SWORD
    multipliers: { fighting: 1.5, foraging: 1.5, excavation: 1.5 }
  ranger:
    name: '&aRanger'
    icon: BOW
    multipliers: { archery: 1.5, fishing: 1.5, agility: 1.5 }
  tanker:
    name: '&9Tanker'
    icon: SHIELD
    multipliers: { defense: 1.5, mining: 1.5 }
  mage:
    name: '&5Mage'
    icon: NETHER_STAR
    multipliers: { farming: 1.5, enchanting: 1.5, alchemy: 1.5 }
