gui:
  title: "&8ᴄᴀᴛᴀᴄʟʏsᴍ ᴄʟᴀss"
  size: 27

classes:

  fighter:
    display-name: "&cFighter"
    material: "IRON_SWORD"
    slot: 10
    group: "fighter"

    lore:
      - ""
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ғɪɢʜᴛɪɴɢ &e1.𝟻x"
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ᴇxᴄᴀᴠᴀᴛɪᴏɴ &e1.𝟻x"
      - "&𝟽> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ғᴏʀᴀɢɪɴɢ &e1.5x"
      - ""
      - "&eᴋʟɪᴋ ᴜɴᴛᴜᴋ ᴍᴇᴍɪʟɪʜ ᴄʟᴀss"

  ranger:
    display-name: "&aRanger"
    material: "BOW"
    slot: 12
    group: "ranger"

    lore:
      - ""
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ᴀʀᴄʜᴇʀʏ &e1.𝟻x"
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ᴀɢɪʟɪᴛʏ &e1.5x"
      - "&8> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ғɪsʜɪɴɢ &e1.5x"
      - ""
      - "&eᴋʟɪᴋ ᴜɴᴛᴜᴋ ᴍᴇᴍɪʟɪʜ ᴄʟᴀss"

  tanker:
    display-name: "&bTanker"
    material: "SHIELD"
    slot: 14
    group: "tanker"

    lore:
      - ""
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ᴅᴇғᴇɴsᴇ &e1.5x"
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ᴍɪɴɪɴɢ &e1.5x"
      - ""
      - "&eᴋʟɪᴋ ᴜɴᴛᴜᴋ ᴍᴇᴍɪʟɪʜ ᴄʟᴀss"

  mage:
    display-name: "&5Mage"
    material: "BLAZE_ROD"
    slot: 16
    group: "mage"

    lore:
      - ""
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ғᴀʀᴍɪɴɢ &e1.5x"
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ᴇɴᴄʜᴀɴᴛɪɴɢ &e1.5x"
      - "&7> &fʙᴏᴏsᴛ xᴘ sᴋɪʟʟ ᴀʟᴄʜᴇᴍʏ &e1.5x"
      - ""
      - "&eᴋʟɪᴋ ᴜɴᴛᴜᴋ ᴍᴇᴍɪʟɪʜ ᴄʟᴀss"

messages:
  selected: "&cCataclysmClass &fBerhasil memilih class &e{class}&f!"
  reloaded: "&cCataclysmClass &fConfig berhasil di-reload."
